services:
  finlog-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: prod
    container_name: finlog-fe
    restart: always
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=prod
    volumes:
      - .:/app
      - /app/node_modules
