services:
  finlog-fe:
    build:
      context: .
      dockerfile: dev.Dockerfile
      target: dev
    container_name: finlog-fe
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules